version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
